USE [master]
GO

/****** Object:  Database [dbInventory]    Script Date: 06/09/2021 09:43:33 p. m. ******/
CREATE DATABASE [dbInventory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbInventory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\dbInventory2.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbInventory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\dbInventory_log2.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbInventory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbInventory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbInventory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbInventory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbInventory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbInventory] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbInventory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbInventory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbInventory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbInventory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbInventory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbInventory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbInventory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbInventory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbInventory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbInventory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbInventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbInventory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbInventory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbInventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbInventory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbInventory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbInventory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbInventory] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbInventory] SET  MULTI_USER 
GO

ALTER DATABASE [dbInventory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbInventory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbInventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbInventory] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbInventory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbInventory] SET QUERY_STORE = OFF
GO

USE [dbInventory]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [dbInventory] SET  READ_WRITE 
GO


